---
openapi: 3.1.0
paths:
  /:
    get:
      parameters:
      - name: count
        in: query
        schema:
          type: integer
          format: int32
      - name: id
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
    delete:
      parameters:
      - name: count
        in: query
        schema:
          type: integer
          format: int32
      - name: id
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /jwt:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
info:
  title: Generated API
  version: "1.0"
